### ISSUE TITLE
Add a simple sale transaction

### ISSUE THREAD

**Issue by nicolasard** [ePosnet/SOAP_API_Basic_examples#2]
It should be good to have a simple Sale transaction example XML. 

In the RequestExample you have Preauth, PFAC preatuh, etc but not a simple sale.

FYI: @arivasvera

**Comment by nicolasard** [comment]
As we checked we need to change the file name of https://github.com/ePosnet/SOAP_API_Basic_examples/blob/master/RequestExample/IPG_Basic_sale_preauth_transaction.xml to IPG_Basic_sale_transaction.xml because this is already a sale transaction.

**Comment by arivasvera** [comment]
@nicolasard: the file name says "IPG_Basic_**sale**_**preauth**_transaction.xml" because the message is the same for both sales and preauths requests.

to keep keeping a single example for these two request types, I think we could change the name to IPG_Basic_sale_**or**_preauth_transaction.xml

So, could you please make the change and update the PR?

**Comment by nicolasard** [comment]
Maybe we can merge this PR, and add a new PR for a Preauth example to keep examples clear.
